services:
  - type: web
    name: nhattin-api
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start:pro
    healthCheckPath: /docs
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: product
      - key: PORT
        value: 10000
      - key: MONGOURL
        sync: false
      - key: DATABASE
        sync: false  
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false 